# from sqlalchemy import Column, Integer, String, DateTime
# from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER
# from sqlalchemy.ext.declarative import declarative_base
# import uuid

# Base = declarative_base()

# class IncomingCallsSql(Base):
#     __tablename__ = 'IncomingCalls'

#     id = Column(UNIQUEIDENTIFIER, primary_key=True, default=uuid.uuid4)
#     cdrRecordType = Column(Integer)
#     globalCallID_callManagerId = Column(Integer)
#     globalCallID_callId = Column(Integer)
#     origLegCallIdentifier = Column(Integer)
#     dateTimeOrigination = Column(Integer)
#     origNodeId = Column(Integer, nullable=True)
#     origSpan = Column(Integer, nullable=True)
#     origIpAddr = Column(String, nullable=True)
#     callingPartyNumber = Column(String, nullable=True)
#     callingPartyUnicodeLoginUserID = Column(String, nullable=True)
#     origCause_location = Column(Integer, nullable=True)
#     origCause_value = Column(Integer, nullable=True)
#     origPrecedenceLevel = Column(Integer, nullable=True)
#     origMediaTransportAddress_IP = Column(String, nullable=True)
#     origMediaTransportAddress_Port = Column(Integer, nullable=True)
#     origMediaCap_payloadCapability = Column(Integer, nullable=True)
#     origMediaCap_maxFramesPerPacket = Column(Integer, nullable=True)
#     origMediaCap_g723BitRate = Column(Integer, nullable=True)
#     origVideoCap_Codec = Column(Integer, nullable=True)
#     origVideoCap_Bandwidth = Column(Integer, nullable=True)
#     origVideoCap_Resolution = Column(Integer, nullable=True)
#     origVideoTransportAddress_IP = Column(String, nullable=True)
#     origVideoTransportAddress_Port = Column(Integer, nullable=True)
#     origRSVPAudioStat = Column(Integer, nullable=True)
#     origRSVPVideoStat = Column(Integer, nullable=True)
#     destLegIdentifier = Column(String, nullable=True)
#     destNodeId = Column(Integer, nullable=True)
#     destSpan = Column(Integer, nullable=True)
#     destIpAddr = Column(String, nullable=True)
#     originalCalledPartyNumber = Column(String, nullable=True)
#     finalCalledPartyNumber = Column(String, nullable=True)
#     finalCalledPartyUnicodeLoginUserID = Column(String, nullable=True)
#     destCause_location = Column(Integer, nullable=True)
#     destCause_value = Column(Integer, nullable=True)
#     destPrecedenceLevel = Column(Integer, nullable=True)
#     destMediaTransportAddress_IP = Column(String, nullable=True)
#     destMediaTransportAddress_Port = Column(Integer, nullable=True)
#     destMediaCap_payloadCapability = Column(Integer, nullable=True)
#     destMediaCap_maxFramesPerPacket = Column(Integer, nullable=True)
#     destMediaCap_g723BitRate = Column(Integer, nullable=True)
#     destVideoCap_Codec = Column(Integer, nullable=True)
#     destVideoCap_Bandwidth = Column(Integer, nullable=True)
#     destVideoCap_Resolution = Column(Integer, nullable=True)
#     destVideoTransportAddress_IP = Column(String, nullable=True)
#     destVideoTransportAddress_Port = Column(Integer, nullable=True)
#     destRSVPAudioStat = Column(String, nullable=True)
#     destRSVPVideoStat = Column(String, nullable=True)
#     dateTimeConnect = Column(Integer, nullable=True)
#     dateTimeDisconnect = Column(Integer, nullable=True)
#     lastRedirectDn = Column(String, nullable=True)
#     pkid = Column(String, nullable=True)
#     originalCalledPartyNumberPartition = Column(String, nullable=True)
#     callingPartyNumberPartition = Column(String, nullable=True)
#     finalCalledPartyNumberPartition = Column(String, nullable=True)
#     lastRedirectDnPartition = Column(String, nullable=True)
#     duration = Column(Integer, nullable=True)
#     origDeviceName = Column(String, nullable=True)
#     destDeviceName = Column(String, nullable=True)
#     origCallTerminationOnBehalfOf = Column(Integer, nullable=True)
#     destCallTerminationOnBehalfOf = Column(Integer, nullable=True)
#     origCalledPartyRedirectOnBehalfOf = Column(Integer, nullable=True)
#     lastRedirectRedirectOnBehalfOf = Column(Integer, nullable=True)
#     origCalledPartyRedirectReason = Column(Integer, nullable=True)
#     lastRedirectRedirectReason = Column(Integer, nullable=True)
#     destConversationId = Column(String, nullable=True)
#     globalCallId_ClusterID = Column(String, nullable=True)
#     joinOnBehalfOf = Column(Integer, nullable=True)
#     comment = Column(String, nullable=True)
#     authCodeDescription = Column(String, nullable=True)
#     authorizationLevel = Column(Integer, nullable=True)
#     clientMatterCode = Column(String, nullable=True)
#     origDTMFMethod = Column(Integer, nullable=True)
#     destDTMFMethod = Column(Integer, nullable=True)
#     callSecuredStatus = Column(Integer, nullable=True)
#     origConversationId = Column(String, nullable=True)
#     origMediaCap_Bandwidth = Column(Integer, nullable=True)
#     destMediaCap_Bandwidth = Column(Integer, nullable=True)
#     authorizationCodeValue = Column(String, nullable=True)
#     outpulsedCallingPartyNumber = Column(String, nullable=True)
#     outpulsedCalledPartyNumber = Column(String, nullable=True)
#     origIpv4v6Addr = Column(String, nullable=True)
#     destIpv4v6Addr = Column(String, nullable=True)
#     origVideoCap_Codec_Channel2 = Column(Integer, nullable=True)
#     origVideoCap_Bandwidth_Channel2 = Column(Integer, nullable=True)
#     origVideoCap_Resolution_Channel2 = Column(Integer, nullable=True)
#     origVideoTransportAddress_IP_Channel2 = Column(String, nullable=True)
#     origVideoTransportAddress_Port_Channel2 = Column(Integer, nullable=True)
#     origVideoChannel_Role_Channel2 = Column(Integer, nullable=True)
#     destVideoCap_Codec_Channel2 = Column(Integer, nullable=True)
#     destVideoCap_Bandwidth_Channel2 = Column(Integer, nullable=True)
#     destVideoCap_Resolution_Channel2 = Column(Integer, nullable=True)
#     destVideoTransportAddress_IP_Channel2 = Column(String, nullable=True)
#     destVideoTransportAddress_Port_Channel2 = Column(Integer, nullable=True)
#     destVideoChannel_Role_Channel2 = Column(Integer, nullable=True)
#     IncomingProtocolID = Column(Integer, nullable=True)
#     IncomingProtocolCallRef = Column(String, nullable=True)
#     OutgoingProtocolID = Column(Integer, nullable=True)
#     OutgoingProtocolCallRef = Column(String, nullable=True)
#     currentRoutingReason = Column(Integer, nullable=True)
#     origRoutingReason = Column(Integer, nullable=True)
#     lastRedirectingRoutingReason = Column(Integer, nullable=True)
#     huntPilotPartition = Column(String, nullable=True)
#     huntPilotDN = Column(String, nullable=True)
#     calledPartyPatternUsage = Column(Integer, nullable=True)
#     IncomingICID = Column(String, nullable=True)
#     IncomingOrigIOI = Column(String, nullable=True)
#     IncomingTermIOI = Column(String, nullable=True)
#     OutgoingICID = Column(String, nullable=True)
#     OutgoingOrigIOI = Column(String, nullable=True)
#     OutgoingTermIOI = Column(String, nullable=True)
#     outpulsedOriginalCalledPartyNumber = Column(String, nullable=True)
#     outpulsedLastRedirectingNumber = Column(String, nullable=True)
#     wasCallQueued = Column(Integer, nullable=True)
#     totalWaitTimeInQueue = Column(Integer, nullable=True)
#     callingPartyNumber_uri = Column(String, nullable=True)
#     originalCalledPartyNumber_uri = Column(String, nullable=True)
#     finalCalledPartyNumber_uri = Column(String, nullable=True)
#     lastRedirectDn_uri = Column(String, nullable=True)
#     mobileCallingPartyNumber = Column(String, nullable=True)
#     finalMobileCalledPartyNumber = Column(String, nullable=True)
#     origMobileDeviceName = Column(String, nullable=True)
#     destMobileDeviceName = Column(String, nullable=True)
#     origMobileCallDuration = Column(Integer, nullable=True)
#     destMobileCallDuration = Column(Integer, nullable=True)
#     mobileCallType = Column(Integer, nullable=True)
#     originalCalledPartyPattern = Column(String, nullable=True)
#     finalCalledPartyPattern = Column(String, nullable=True)
#     lastRedirectingPartyPattern = Column(String, nullable=True)
#     huntPilotPattern = Column(String, nullable=True)