// const database = "cdr";
// const collection = "incoming_calls";

// // Create a new database.
// use(database);

// Define the JSON schema for validation
const schema = {
  bsonType: "object",
  required: ["cdrRecordType", "globalCallID_callManagerId", "globalCallID_callId", "origLegCallIdentifier", "dateTimeOrigination", "origNodeId", "origSpan", "origIpAddr", "callingPartyNumber", "callingPartyUnicodeLoginUserID", "origCause_location", "origCause_value", "origPrecedenceLevel", "origMediaTransportAddress_IP", "origMediaTransportAddress_Port", "origMediaCap_payloadCapability", "origMediaCap_maxFramesPerPacket", "origMediaCap_g723BitRate", "origVideoCap_Codec", "origVideoCap_Bandwidth", "origVideoCap_Resolution", "origVideoTransportAddress_IP", "origVideoTransportAddress_Port", "origRSVPAudioStat", "origRSVPVideoStat", "destLegIdentifier", "destNodeId", "destSpan", "destIpAddr", "originalCalledPartyNumber", "finalCalledPartyNumber", "finalCalledPartyUnicodeLoginUserID", "destCause_location", "destCause_value", "destPrecedenceLevel", "destMediaTransportAddress_IP", "destMediaTransportAddress_Port", "destMediaCap_payloadCapability", "destMediaCap_maxFramesPerPacket", "destMediaCap_g723BitRate", "destVideoCap_Codec", "destVideoCap_Bandwidth", "destVideoCap_Resolution", "destVideoTransportAddress_IP", "destVideoTransportAddress_Port", "destRSVPAudioStat", "destRSVPVideoStat", "dateTimeConnect", "dateTimeDisconnect", "lastRedirectDn", "pkid", "originalCalledPartyNumberPartition", "callingPartyNumberPartition", "finalCalledPartyNumberPartition", "lastRedirectDnPartition", "duration", "origDeviceName", "destDeviceName", "origCallTerminationOnBehalfOf", "destCallTerminationOnBehalfOf", "origCalledPartyRedirectOnBehalfOf", "lastRedirectRedirectOnBehalfOf", "origCalledPartyRedirectReason", "lastRedirectRedirectReason", "destConversationId", "globalCallId_ClusterID", "joinOnBehalfOf", "comment", "authCodeDescription", "authorizationLevel", "clientMatterCode", "origDTMFMethod", "destDTMFMethod", "callSecuredStatus", "origConversationId", "origMediaCap_Bandwidth", "destMediaCap_Bandwidth", "authorizationCodeValue", "outpulsedCallingPartyNumber", "outpulsedCalledPartyNumber", "origIpv4v6Addr", "destIpv4v6Addr", "origVideoCap_Codec_Channel2", "origVideoCap_Bandwidth_Channel2", "origVideoCap_Resolution_Channel2", "origVideoTransportAddress_IP_Channel2", "origVideoTransportAddress_Port_Channel2", "origVideoChannel_Role_Channel2", "destVideoCap_Codec_Channel2", "destVideoCap_Bandwidth_Channel2", "destVideoCap_Resolution_Channel2", "destVideoTransportAddress_IP_Channel2", "destVideoTransportAddress_Port_Channel2", "destVideoChannel_Role_Channel2", "IncomingProtocolID", "IncomingProtocolCallRef", "OutgoingProtocolID", "OutgoingProtocolCallRef", "currentRoutingReason", "origRoutingReason", "lastRedirectingRoutingReason", "huntPilotPartition", "huntPilotDN", "calledPartyPatternUsage", "IncomingICID", "IncomingOrigIOI", "IncomingTermIOI", "OutgoingICID", "OutgoingOrigIOI", "OutgoingTermIOI", "outpulsedOriginalCalledPartyNumber", "outpulsedLastRedirectingNumber", "wasCallQueued", "totalWaitTimeInQueue", "callingPartyNumber_uri", "originalCalledPartyNumber_uri", "finalCalledPartyNumber_uri", "lastRedirectDn_uri", "mobileCallingPartyNumber", "finalMobileCalledPartyNumber", "origMobileDeviceName", "destMobileDeviceName", "origMobileCallDuration", "destMobileCallDuration", "mobileCallType", "originalCalledPartyPattern", "finalCalledPartyPattern", "lastRedirectingPartyPattern", "huntPilotPattern"],
  properties: {
    cdrRecordType: { bsonType: "int" },
    globalCallID_callManagerId: { bsonType: "int" },
    globalCallID_callId: { bsonType: "int" },
    origLegCallIdentifier: { bsonType: "int" },
    dateTimeOrigination: { bsonType: "int" },
    origNodeId: { bsonType: "int" },
    origSpan: { bsonType: "int" },
    origIpAddr: { bsonType: "int" },
    callingPartyNumber: { bsonType: "string" },
    callingPartyUnicodeLoginUserID: { bsonType: "string" },
    origCause_location: { bsonType: "int" },
    origCause_value: { bsonType: "int" },
    origPrecedenceLevel: { bsonType: "int" },
    origMediaTransportAddress_IP: { bsonType: "int" },
    origMediaTransportAddress_Port: { bsonType: "int" },
    origMediaCap_payloadCapability: { bsonType: "int" },
    origMediaCap_maxFramesPerPacket: { bsonType: "int" },
    origMediaCap_g723BitRate: { bsonType: "int" },
    origVideoCap_Codec: { bsonType: "int" },
    origVideoCap_Bandwidth: { bsonType: "int" },
    origVideoCap_Resolution: { bsonType: "int" },
    origVideoTransportAddress_IP: { bsonType: "int" },
    origVideoTransportAddress_Port: { bsonType: "int" },
    origRSVPAudioStat: { bsonType: "int" },
    origRSVPVideoStat: { bsonType: "int" },
    destLegIdentifier: { bsonType: "string" },
    destNodeId: { bsonType: "int" },
    destSpan: { bsonType: "int" },
    destIpAddr: { bsonType: "int" },
    originalCalledPartyNumber: { bsonType: "string" },
    finalCalledPartyNumber: { bsonType: "string" },
    finalCalledPartyUnicodeLoginUserID: { bsonType: "string" },
    destCause_location: { bsonType: "int" },
    destCause_value: { bsonType: "int" },
    destPrecedenceLevel: { bsonType: "int" },
    destMediaTransportAddress_IP: { bsonType: "int" },
    destMediaTransportAddress_Port: { bsonType: "int" },
    destMediaCap_payloadCapability: { bsonType: "int" },
    destMediaCap_maxFramesPerPacket: { bsonType: "int" },
    destMediaCap_g723BitRate: { bsonType: "int" },
    destVideoCap_Codec: { bsonType: "int" },
    destVideoCap_Bandwidth: { bsonType: "int" },
    destVideoCap_Resolution: { bsonType: "int" },
    destVideoTransportAddress_IP: { bsonType: "int" },
    destVideoTransportAddress_Port: { bsonType: "int" },
    destRSVPAudioStat: { bsonType: "string" },
    destRSVPVideoStat: { bsonType: "string" },
    dateTimeConnect: { bsonType: "int" },
    dateTimeDisconnect: { bsonType: "int" },
    lastRedirectDn: { bsonType: "string" },
    pkid: { bsonType: "string" },
    originalCalledPartyNumberPartition: { bsonType: "string" },
    callingPartyNumberPartition: { bsonType: "string" },
    finalCalledPartyNumberPartition: { bsonType: "string" },
    lastRedirectDnPartition: { bsonType: "string" },
    duration: { bsonType: "int" },
    origDeviceName: { bsonType: "string" },
    destDeviceName: { bsonType: "string" },
    origCallTerminationOnBehalfOf: { bsonType: "int" },
    destCallTerminationOnBehalfOf: { bsonType: "int" },
    origCalledPartyRedirectOnBehalfOf: { bsonType: "int" },
    lastRedirectRedirectOnBehalfOf: { bsonType: "int" },
    origCalledPartyRedirectReason: { bsonType: "int" },
    lastRedirectRedirectReason: { bsonType: "int" },
    destConversationId: { bsonType: "string" },
    globalCallId_ClusterID: { bsonType: "string" },
    joinOnBehalfOf: { bsonType: "int" },
    comment: { bsonType: "string" },
    authCodeDescription: { bsonType: "string" },
    authorizationLevel: { bsonType: "int" },
    clientMatterCode: { bsonType: "string" },
    origDTMFMethod: { bsonType: "int" },
    destDTMFMethod: { bsonType: "int" },
    callSecuredStatus: { bsonType: "int" },
    origConversationId: { bsonType: "string" },
    origMediaCap_Bandwidth: { bsonType: "int" },
    destMediaCap_Bandwidth: { bsonType: "int" },
    authorizationCodeValue: { bsonType: "string" },
    outpulsedCallingPartyNumber: { bsonType: "string" },
    outpulsedCalledPartyNumber: { bsonType: "string" },
    origIpv4v6Addr: { bsonType: "string" },
    destIpv4v6Addr: { bsonType: "string" },
    origVideoCap_Codec_Channel2: { bsonType: "int" },
    origVideoCap_Bandwidth_Channel2: { bsonType: "int" },
    origVideoCap_Resolution_Channel2: { bsonType: "int" },
    origVideoTransportAddress_IP_Channel2: { bsonType: "int" },
    origVideoTransportAddress_Port_Channel2: { bsonType: "int" },
    origVideoChannel_Role_Channel2: { bsonType: "int" },
    destVideoCap_Codec_Channel2: { bsonType: "int" },
    destVideoCap_Bandwidth_Channel2: { bsonType: "int" },
    destVideoCap_Resolution_Channel2: { bsonType: "int" },
    destVideoTransportAddress_IP_Channel2: { bsonType: "int" },
    destVideoTransportAddress_Port_Channel2: { bsonType: "int" },
    destVideoChannel_Role_Channel2: { bsonType: "int" },
    IncomingProtocolID: { bsonType: "int" },
    IncomingProtocolCallRef: { bsonType: "string" },
    OutgoingProtocolID: { bsonType: "int" },
    OutgoingProtocolCallRef: { bsonType: "string" },
    currentRoutingReason: { bsonType: "int" },
    origRoutingReason: { bsonType: "int" },
    lastRedirectingRoutingReason: { bsonType: "int" },
    huntPilotPartition: { bsonType: "string" },
    huntPilotDN: { bsonType: "string" },
    calledPartyPatternUsage: { bsonType: "int" },
    IncomingICID: { bsonType: "string" },
    IncomingOrigIOI: { bsonType: "string" },
    IncomingTermIOI: { bsonType: "string" },
    OutgoingICID: { bsonType: "string" },
    OutgoingOrigIOI: { bsonType: "string" },
    OutgoingTermIOI: { bsonType: "string" },
    outpulsedOriginalCalledPartyNumber: { bsonType: "string" },
    outpulsedLastRedirectingNumber: { bsonType: "string" },
    wasCallQueued: { bsonType: "int" },
    totalWaitTimeInQueue: { bsonType: "int" },
    callingPartyNumber_uri: { bsonType: "string" },
    originalCalledPartyNumber_uri: { bsonType: "string" },
    finalCalledPartyNumber_uri: { bsonType: "string" },
    lastRedirectDn_uri: { bsonType: "string" },
    mobileCallingPartyNumber: { bsonType: "string" },
    finalMobileCalledPartyNumber: { bsonType: "string" },
    origMobileDeviceName: { bsonType: "string" },
    destMobileDeviceName: { bsonType: "string" },
    origMobileCallDuration: { bsonType: "int" },
    destMobileCallDuration: { bsonType: "int" },
    mobileCallType: { bsonType: "int" },
    originalCalledPartyPattern: { bsonType: "string" },
    finalCalledPartyPattern: { bsonType: "string" },
    lastRedirectingPartyPattern: { bsonType: "string" },
    huntPilotPattern: { bsonType: "string" }
  }
};

// Create a new collection with clustered index and validation
db.createCollection(collection, {
  clusteredIndex: { key: { _id: 1 }, unique: true },
  validator: { $jsonSchema: schema },
  validationLevel: "strict",
  validationAction: "error"
});